#!/bin/bash
#
# Init script to start the Ratio Console as unprivileged user but
# using a lower port through an iptables redirection
#

publicPort=80
internalPort=3000
lockFile=/var/lock/ratioConsole

#iptables -t nat -A PREROUTING -i eth0 -p tcp --dport $publicPort -j REDIRECT --to-port $internalPort
/bin/su - pi -c 'cd ~/dqr/ratio-console && /home/pi/.rvm/gems/ruby-2.2.0/bin/rails s --binding=0.0.0.0'

